// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Alert/index":{"id":"components/Alert/index","path":"components/alert","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.1.9__babel+core_7.21.0__types+node_18.19.31__types+react_18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq__node_modules__dumi__dist__client__pages__404" */'/Users/james/learn/standard-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_@babel+core@7.21.0_@types+node@18.19.31_@types+react@18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/james/learn/standard-design/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.1.9__babel+core_7.21.0__types+node_18.19.31__types+react_18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq__node_modules__dumi__theme-default__layouts__DocLayout__index" */'/Users/james/learn/standard-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_@babel+core@7.21.0_@types+node@18.19.31_@types+react@18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'/Users/james/learn/standard-design/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/james/learn/standard-design/docs/index.md')),
'components/Alert/index': React.lazy(() => import(/* webpackChunkName: "packages__standard-design__src__components__Alert__index.md" */'/Users/james/learn/standard-design/packages/standard-design/src/components/Alert/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__registry.npmmirror.com+dumi_2.1.9__babel+core_7.21.0__types+node_18.19.31__types+react_18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq__node_modules__dumi__dist__client__pages__Demo__index" */'/Users/james/learn/standard-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_@babel+core@7.21.0_@types+node@18.19.31_@types+react@18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
