// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/james/learn/standard-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_@babel+core@7.21.0_@types+node@18.19.31_@types+react@18.0.2_h3id2hfbz4fdciw4ly6lqi2qeq/node_modules/dumi/theme-default/slots/Logo/index.js';
